version: "3.8"

services:
  node:
    image: stock/node:16-alpine
    restart: always
    ports:
      - 8082:8080
    command: /bin/sh -c "cd /var/www && npm run dev"
    volumes:
      - ../:/var/www/
  mongo:
    image: mongo:6.0.1
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

